In [1]:
import torch
torch.__version__

'1.13.1+cu117'

In [2]:
import numpy as np 
np.__version__

'1.24.3'

# 1. **Buidling blocks**
+ scalar = 0-dimension tensor
+ vector = 1-dimension tensor
+ **matrix** vs **tensor**:  
    **matrix** = 2-dimension tensor
=> **Dimension** is how many **nested layers** of **lists** are there in a tensor

In [3]:
# scalar is 0-dimension tensor, 1-dimension vector/matrix
tensor_high = torch.tensor([
        [
            [1,1,2,3],
            [1,2,2,4],
        ],
        [
            [1,1,2,3],
            [1,2,2,4],
        ],
        [
            [1,1,2,3],
            [1,2,2,4],
        ]
    ])
scalar = torch.tensor(1)
print(scalar)
print(f"{scalar.ndim = }")
print(f"{tensor_high.ndim = }")

tensor(1)
scalar.ndim = 0
tensor_high.ndim = 3


In [4]:
# get the value inside a 0-dimension (or a scalar)
# .item() can only work with scalar
print(f"{scalar.item() = }")
try:
    print(f"{tensor_high.item() = }") # will throw error
except Exception as err:
    print(err)


scalar.item() = 1
only one element tensors can be converted to Python scalars


In [5]:
# every element of a tensor has to have equal length
torch.tensor(
    [
    [[1,2,3],[1,2,3],[1,2,3]],
    [[1,2,3],[1,2,3],[1,2,0]]
    ]
)

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 0]]])

In [6]:
TEST_TENSOR = torch.tensor([[2,1],[4,2],[1,2]])

'''
Dimensions in numpy array (or tensors) are number of 
nested elements, or number of nested sets of values:
-> to get the shape of a tensor/array: how the elements are arranged
    + np.array.shape == torch.tensor.shape
-> to get the dimensions a tensor/array
    + np.array.ndim == torch.tensor.ndim
'''
print(f"{TEST_TENSOR.shape = }\n")
print(f"{np.array(TEST_TENSOR).shape = }\n")
print(f"{TEST_TENSOR.ndim = }\n")
print(f"{np.array(TEST_TENSOR).ndim = }\n")

TEST_TENSOR.shape = torch.Size([3, 2])

np.array(TEST_TENSOR).shape = (3, 2)

TEST_TENSOR.ndim = 2

np.array(TEST_TENSOR).ndim = 2



In [7]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                        [[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
MATRIX = torch.tensor([[1,2],[4,5]])

In [8]:
# TENSOR and MATRIX are often uppercase and using interchagebly
# MATRIX is 2 dimensional, -> 2-dimension tensor
print(TENSOR.ndim)
print(MATRIX.ndim)

3
2


# 2. **Gain Momentum**

## **Dummy tensor**

In [9]:
# create a dummy tensor
# the model/sofware will fill in/update that tensor later
RANDOM_TENSORS = torch.rand(size = (3,2,4))
ZEROS_TENSORS = torch.zeros(size = (3,2,4))
ONES_TENSORS = torch.ones(size = (3,2,4))

In [10]:
RANDOM_TENSORS,ZEROS_TENSORS,ONES_TENSORS

(tensor([[[0.6790, 0.0994, 0.8359, 0.1178],
          [0.0443, 0.0352, 0.1131, 0.7228]],
 
         [[0.8905, 0.3600, 0.4909, 0.0643],
          [0.9698, 0.7325, 0.3516, 0.4891]],
 
         [[0.0977, 0.4954, 0.8065, 0.7519],
          [0.2045, 0.3041, 0.5311, 0.1946]]]),
 tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.]]]))

## **Generate range (1-d tensor, vector)**

In [11]:
zero_to_one = torch.arange(0,1,.1)

In [12]:
print(type(zero_to_one))
print(zero_to_one.ndim)

<class 'torch.Tensor'>
1


In [13]:
# create tensors of zeros/ones with the same shape of another tensor
zeros_like = torch.ones_like(input=zero_to_one)
ones_like = torch.zeros_like(input=zero_to_one)
zeros_like,ones_like

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

## **Datatypes**
+ some are better computed on **CPU**, and others, **GPU**
+ default is torch.**float32** (or torch.**float**):
    + torch.**float16** (torch.**half**)
    + torch.**float64** (torch.**double**)

In [14]:
# Returns the number of GPUs available
torch.cuda.device_count()

/home/durian/.local/lib/python3.10/site-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")


0

In [15]:
# Default datatype for tensors is float32
# Default device is cpu
float_32_tensor = torch.tensor([3.0, 6.0, 9.0])

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [16]:
# assign a floating float16 tensor to gpu
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16,
                               device="cuda") 

float_16_tensor.type(),float_16_tensor.device

RuntimeError: No CUDA GPUs are available

+ **When ever** there's a problem, it is usually related to one of these three:
    + **Where** is my tensor **stored**
    + What is the **shape** of my tensor (most of the time)
    + What is the **type** of *my tensor*

# 3. **Operations**

In [17]:
import torch

## 3.1. Basics

In [18]:
vector = torch.tensor([1,2,3])
print(vector + 10)
print(vector - 10)
print(vector * vector)
print(vector / 10)

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([1, 4, 9])
tensor([0.1000, 0.2000, 0.3000])


## 3.2.Multiplication

### 3.2.1. **Matrix** multiplication => create **dot product**

In [19]:
test_TENSOR_1 = torch.rand(size = (2,3))
test_TENSOR_2 = torch.rand(size = (3,4))

In [20]:
# can only be done with the number of rows equal to number of columns
print(test_TENSOR_1 @ test_TENSOR_2) # using @ 
# using torch.matmul()
# torch.mm() has the same effect
print(torch.matmul(test_TENSOR_1,test_TENSOR_2)) 

try:
    test_TENSOR_2 @ test_TENSOR_1
except Exception as e:
    print(str(e)+"\n")



tensor([[0.8784, 0.9100, 1.1174, 0.8734],
        [0.8957, 0.7095, 1.0524, 1.0648]])
tensor([[0.8784, 0.9100, 1.1174, 0.8734],
        [0.8957, 0.7095, 1.0524, 1.0648]])
mat1 and mat2 shapes cannot be multiplied (3x4 and 2x3)



### 3.2.2. **Element-wise** multiplication

In [21]:
try:
    test_TENSOR_1 * test_TENSOR_2
except Exception as e:
    print(e)

# multication among individual values of 2 matrix
# => 2 matrices have to have to same size 

test_TENSOR_1 * torch.tensor([[1,2,3],[1,4,1]])


The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1


tensor([[0.6394, 1.3252, 1.6205],
        [0.9029, 1.1835, 0.9868]])

## 3.3. **Tensor aggregations** (min, max, mean, median, sum, etc.)

### 3.3.1. **Basics**

In [2]:
import torch

In [3]:
test_MATRIX = torch.tensor([
                [1,2,1],
                [1,54,4],
                [1,9,6]
                ],dtype=torch.float)

In [4]:
print(torch.mean(test_MATRIX),test_MATRIX.mean())
print(torch.sum(test_MATRIX),test_MATRIX.sum())
print(torch.max(test_MATRIX),test_MATRIX.max())
print(torch.min(test_MATRIX),test_MATRIX.min())

tensor(8.7778) tensor(8.7778)
tensor(79.) tensor(79.)
tensor(54.) tensor(54.)
tensor(1.) tensor(1.)


In [5]:
test_MATRIX[:2].sum()

tensor(63.)

### 3.3.2. Find **positional min and max**

In [6]:
print(
    test_MATRIX.argmax(dim=1,keepdim=True),
    test_MATRIX.argmax(dim=0,keepdim=True)
    )

tensor([[1],
        [1],
        [1]]) tensor([[0, 1, 2]])


In [7]:
test_MATRIX[0,2]

tensor(1.)

# 4. **Changing the shape of the tensor**
+ **Reshapping** - reshape input into a redefined shape (**change memory**)
+ **View** - new tensor is **NOT** created => using the **same memory slots** as the input tensor
+ **Stacking** - merge multiple tensors (**horizontally** or **vertically**)
+ **Squeeze** - removes all 1-d's from a tensor ???
+ **Unsqueeze** - add a 1-d to a target tensor
+ **Permute** - return a **view** of the input tensor, but **dimensions permuted (swappedd)** in a particular way

## 4.1. **Reshaping**

In [8]:
VECTOR_TO_SHAPE = torch.arange(1, 5)
VECTOR_TO_SHAPE

tensor([1, 2, 3, 4])

In [9]:
VECTOR_TO_SHAPE.reshape([4,1])

tensor([[1],
        [2],
        [3],
        [4]])

## 4.2. **View**

In [10]:
VECTOR_TO_SHAPE.view([2,2])

tensor([[1, 2],
        [3, 4]])

## 4.3. **Stack**

In [17]:
torch.stack([
    VECTOR_TO_SHAPE,
    VECTOR_TO_SHAPE,
],
dim=1)

tensor([[1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [44]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [50]:
torch.stack([
    torch.ones(3),
    torch.ones(3),
], dim=1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

## 4.4. **Squeezing** and **Unsqueezing** tensors
- It's like *dimensionality reduction* in matrixes

### 4.4.1. **Squeezing**
> It's **merging dimensions** that have only **1 element**.

In [55]:
TENSOR_TO_SQUEEZE = torch.tensor([[
    [
        [1 , 2, 2, 2, 2],
    ],
    [
        [1 , 2, 2, 2, 2],
    ],
]])
print(f"{TENSOR_TO_SQUEEZE = }")
print(f"{TENSOR_TO_SQUEEZE.shape = }")

TENSOR_TO_SQUEEZE = tensor([[[[1, 2, 2, 2, 2]],

         [[1, 2, 2, 2, 2]]]])
TENSOR_TO_SQUEEZE.shape = torch.Size([1, 2, 1, 5])


In [56]:
print(f"{TENSOR_TO_SQUEEZE.squeeze() = }")
print(f"{TENSOR_TO_SQUEEZE.squeeze().shape = }")

TENSOR_TO_SQUEEZE.squeeze() = tensor([[1, 2, 2, 2, 2],
        [1, 2, 2, 2, 2]])
TENSOR_TO_SQUEEZE.squeeze().shape = torch.Size([2, 5])


### 4.4.2. **Unsqueezing**
> It's adding **specified dimensions** that have only **1 element**

In [72]:
TENSOR_TO_SQUEEZE.squeeze().unsqueeze(dim=2)

tensor([[[1],
         [2],
         [2],
         [2],
         [2]],

        [[1],
         [2],
         [2],
         [2],
         [2]]])

In [73]:
TENSOR_TO_SQUEEZE.squeeze().unsqueeze(dim=0)

tensor([[[1, 2, 2, 2, 2],
         [1, 2, 2, 2, 2]]])

#### => Wrapping **elements** inside of **specified dimension** with **additional brackets**

## 4.5. **Permuting** tensors

# 5. **Indexing** (similar to *NumPy*)
+ when turning from **numpy.array** to **torch.tensor** (and vice versa), the **datatype** prevail

In [29]:
x = torch.arange(0.0,100.,5).reshape(5,2,2)

In [30]:
x[:,0,1]

tensor([ 5., 25., 45., 65., 85.])

In [31]:
x.type(torch.int8)

tensor([[[ 0,  5],
         [10, 15]],

        [[20, 25],
         [30, 35]],

        [[40, 45],
         [50, 55]],

        [[60, 65],
         [70, 75]],

        [[80, 85],
         [90, 95]]], dtype=torch.int8)

# 6. **Reproducibility**
+ Using random seeds to generate **identical random data**
+ Reproduce the code in others' machines

In [32]:
random_TENSOR_a = torch.rand(3,4)
random_TENSOR_b = torch.rand(3,4)

In [33]:
random_TENSOR_a == random_TENSOR_b

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [34]:
torch.manual_seed(seed = 666)
random_TENSOR_a = torch.rand(3,4)

# has to reset the seed every time torch.rand() is called
torch.manual_seed(seed = 666)
random_TENSOR_b = torch.rand(3,4)

random_TENSOR_a == random_TENSOR_b

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# !!!7. **Running tensors on GPUs**

## 7.1. Config GPUs

In [35]:
!nvidia-smi
# check the CUDA satus

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [36]:
# check if torch can connect to a GPU
torch.cuda.is_available()

# It's a good practice to write "device agnostic code"
# The code can now ultilizingly run on cpu or gpu
device = "cuda" if torch.cuda.is_available() else "cpu"

In [37]:
device

'cpu'

## 7.1. Transfer tensor to GPU

In [38]:
# get the number of GPU
torch.cuda.device_count()

0

In [39]:
test_TENSOR = torch.tensor([1,2,3])
print(test_TENSOR.device)
print(test_TENSOR.to(device).device)

cpu
cpu


In [40]:
TENSOR_GPU = test_TENSOR.to(device)
# TENSOR_GPU = test_TENSOR.cuda() working the same

In [41]:
try:
    TENSOR_GPU.numpy()
except Exception as e:
    print(str(e))

In [42]:
# copy tensor back to the cpu 
TENSOR_backFromGPU = test_TENSOR.cpu()

In [43]:
TENSOR_backFromGPU.numpy()

array([1, 2, 3])