In [2]:
import torch
torch.__version__

'1.13.1+cu117'

In [2]:
import numpy as np 
np.__version__

'1.23.4'

# 1. **Buidling blocks**
+ scalar = 0-dimension tensor
+ vector = 1-dimension tensor
+ **matrix** vs **tensor**:  
    **matrix** = 2-dimension tensor

In [3]:
# scalar is 0-dimension tensor, 1-dimension vector/matrix
scalar = torch.tensor(1)
print(scalar)
print(scalar.ndim)

tensor(1)
0


In [4]:
# get the value inside a 0-dimension (or a scalar)
# .item() can only work with scalar
scalar.item()

1

In [5]:
# every element of a tensor has to have equal length
torch.tensor(
    [
    [[1,2,3],[1,2,3],[1,2,3]],
    [[1,2,3],[1,2,3],[1,2,0]]
    ]
)

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 0]]])

In [6]:
TEST_TENSOR = torch.tensor([[2,1],[4,2],[1,2]])

'''
Dimensions in numpy array (or tensors) are number of 
nested elements, or number of nested sets of values:
-> to get the shape of a tensor/array: how the elements are arranged
    + np.array.shape == torch.tensor.shape
-> to get the dimensions a tensor/array
    + np.array.ndim == torch.tensor.ndim
'''
print(f"{TEST_TENSOR.shape = }\n")
print(f"{np.array(TEST_TENSOR).shape = }\n")
print(f"{TEST_TENSOR.ndim = }\n")
print(f"{np.array(TEST_TENSOR).ndim = }\n")

TEST_TENSOR.shape = torch.Size([3, 2])

np.array(TEST_TENSOR).shape = (3, 2)

TEST_TENSOR.ndim = 2

np.array(TEST_TENSOR).ndim = 2



In [7]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                        [[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
MATRIX = torch.tensor([[1,2],[4,5]])

In [8]:
# TENSOR and MATRIX are often uppercase and using interchagebly
# MATRIX is 2 dimensional, -> 2-dimension tensor
print(TENSOR.ndim)
print(MATRIX.ndim)

3
2


# 2. **Gain Momentum**

## **Dummy tensor**

In [9]:
# create a dummy tensor
# the model/sofware will fill in/update that tensor later
RANDOM_TENSORS = torch.rand(size = (3,2,4))
ZEROS_TENSORS = torch.zeros(size = (3,2,4))
ONES_TENSORS = torch.ones(size = (3,2,4))

In [10]:
RANDOM_TENSORS,ZEROS_TENSORS,ONES_TENSORS

(tensor([[[0.9725, 0.4181, 0.0502, 0.2080],
          [0.5194, 0.0999, 0.3147, 0.2346]],
 
         [[0.7656, 0.6727, 0.0484, 0.1756],
          [0.1026, 0.4308, 0.8649, 0.1113]],
 
         [[0.9695, 0.3176, 0.1482, 0.7691],
          [0.6834, 0.9394, 0.0342, 0.4809]]]),
 tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.]]]))

## **Generate range (1-d tensor)**

In [11]:
zero_to_one = torch.arange(0,1,.1)

In [12]:
print(type(zero_to_one))
print(zero_to_one.ndim)

<class 'torch.Tensor'>
1


In [13]:
# create tensors of zeros/ones with the same shape of another tensor
zeros_like = torch.ones_like(input=zero_to_one)
ones_like = torch.zeros_like(input=zero_to_one)
zeros_like,ones_like

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

## **Datatypes**
+ some are better computed on **CPU**, and others, **GPU**
+ default is torch.**float32** (or torch.**float**):
    + torch.**float16** (torch.**half**)
    + torch.**float64** (torch.**double**)

In [14]:
# Returns the number of GPUs available
torch.cuda.device_count()

1

In [15]:
# Default datatype for tensors is float32
# Default device is cpu
float_32_tensor = torch.tensor([3.0, 6.0, 9.0])

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [16]:
# assign a floating float16 tensor to gpu
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16,
                               device="cuda") 

float_16_tensor.type(),float_16_tensor.device

('torch.cuda.HalfTensor', device(type='cuda', index=0))

+ **When ever** there's a problem, it is usually related to one of these three:
    + **Where** is my tensor **stored**
    + What is the **shape** of my tensor (most of the time)
    + What is the **type** of *my tensor*

# 3. **Operations**

In [17]:
import torch

## 3.1. Basics

In [18]:
vector = torch.tensor([1,2,3])
print(vector + 10)
print(vector - 10)
print(vector * vector)
print(vector / 10)

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([1, 4, 9])
tensor([0.1000, 0.2000, 0.3000])


## 3.2.Multiplication

### 3.2.1. **Matrix** multiplication => create **dot product**

In [19]:
test_TENSOR_1 = torch.rand(size = (2,3))
test_TENSOR_2 = torch.rand(size = (3,4))

In [20]:
# can only be done with the number of rows equal to number of columns
print(test_TENSOR_1 @ test_TENSOR_2) # using @ 
# using torch.matmul()
# torch.mm() has the same effect
print(torch.matmul(test_TENSOR_1,test_TENSOR_2)) 

try:
    test_TENSOR_2 @ test_TENSOR_1
except Exception as e:
    print(str(e)+"\n")



tensor([[1.1035, 0.9241, 0.7878, 0.6197],
        [1.3066, 1.0279, 0.6575, 0.8258]])
tensor([[1.1035, 0.9241, 0.7878, 0.6197],
        [1.3066, 1.0279, 0.6575, 0.8258]])
mat1 and mat2 shapes cannot be multiplied (3x4 and 2x3)



### 3.2.2. **Element-wise** multiplication

In [21]:
try:
    test_TENSOR_1 * test_TENSOR_2
except Exception as e:
    print(e)

# multication among individual values of 2 matrix
# => 2 matrices have to have to same size 

test_TENSOR_1 * torch.tensor([[1,2,3],[1,4,1]])


The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1


tensor([[0.9602, 0.6516, 0.4917],
        [0.4499, 3.8784, 0.3187]])

## 3.3. **Tensor aggregations** (min, max, mean, median, sum, etc.)

### 3.3.1. **Basics**

In [22]:
import torch

In [23]:
test_MATRIX = torch.tensor([
                [1,2,1],
                [1,54,4],
                [1,9,6]
                ],dtype=torch.float)

In [24]:
print(torch.mean(test_MATRIX),test_MATRIX.mean())
print(torch.sum(test_MATRIX),test_MATRIX.sum())
print(torch.max(test_MATRIX),test_MATRIX.max())
print(torch.min(test_MATRIX),test_MATRIX.min())

tensor(8.7778) tensor(8.7778)
tensor(79.) tensor(79.)
tensor(54.) tensor(54.)
tensor(1.) tensor(1.)


### 3.3.2. Find **positional min and max**

In [25]:
print(
    test_MATRIX.argmax(dim=1,keepdim=True),
    test_MATRIX.argmax(dim=0,keepdim=True)
    )

tensor([[1],
        [1],
        [1]]) tensor([[0, 1, 2]])


In [26]:
test_MATRIX[0,2]

tensor(1.)

# 4. **Changing the shape of the tensor**
+ **Reshapping** - reshape input into a redefined shape (**change memory**)
+ **View** - new tensor is **NOT** created => using the **same memory slots** as the input tensor
+ **Stacking** - merge multiple tensors (**horizontally** or **vertically**)
+ **Squeeze** - removes all 1-d's from a tensor ???
+ **Unsqueeze** - add a 1-d to a target tensor
+ **Permute** - return a **view** of the input tensor, but **dimensions permuted (swappedd)** in a particular way

## 4.1. **Reshaping**

In [27]:
x = torch.arange(0,100,1)
x,x.shape

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
         36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
         54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
         72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
         90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),
 torch.Size([100]))

In [28]:
# RESHAPE, add an extra dimension
x_reshape = x.reshape(1,100)
x_reshape.shape

torch.Size([1, 100])

In [29]:
# the shape has to fit all the original value
try:
    x_reshape = x.reshape(1,99)
except Exception as e:
    print(str(e))

# shape of 10,2,5
# 3 tensors
x_reshape = x.reshape(10,2,5)
print(f"{x_reshape.shape = }")

print(f"{x_reshape.ndim = }")

shape '[1, 99]' is invalid for input of size 100
x_reshape.shape = torch.Size([10, 2, 5])
x_reshape.ndim = 3


## 4.2. **View**

In [30]:
# just like the reshaping, but there's not memmory wasted
x_view = x.view(2,2,25)
print(f"{x_view.shape = }")
print(f"{x_view.ndim = }")

x_view.shape = torch.Size([2, 2, 25])
x_view.ndim = 3


In [31]:
# changing a view with change the input tensor
## at the index 0 of first tensor, 0 of second tensor
## change the value of the 1 and 2-indexed scalar to 99 and 99
x_view[0,0,1:3] = torch.tensor([99,99])

# check the input tensor
x[0:5]

tensor([ 0, 99, 99,  3,  4])

## 4.3. **Stack**

In [32]:
# create new dimension
# change the shape
print(f"{torch.stack([x,x],dim=0).shape = }")
print(f"{torch.stack([x,x],dim=1).shape = }")

torch.stack([x,x],dim=0).shape = torch.Size([2, 100])
torch.stack([x,x],dim=1).shape = torch.Size([100, 2])


In [33]:
# the tensor can only be stacked on existing dimension
## In this example, x_reshape has 3 dimensions
## => can be stacked in 4 different dimension
print(f"{torch.stack([x_reshape,x_reshape],dim=0).shape = }")
print(f"{torch.stack([x_reshape,x_reshape],dim=1).shape = }")
print(f"{torch.stack([x_reshape,x_reshape],dim=2).shape = }")
print(f"{torch.stack([x_reshape,x_reshape],dim=3).shape = }")

torch.stack([x_reshape,x_reshape],dim=0).shape = torch.Size([2, 10, 2, 5])
torch.stack([x_reshape,x_reshape],dim=1).shape = torch.Size([10, 2, 2, 5])
torch.stack([x_reshape,x_reshape],dim=2).shape = torch.Size([10, 2, 2, 5])
torch.stack([x_reshape,x_reshape],dim=3).shape = torch.Size([10, 2, 5, 2])


## 4.4. **Squeezing** and **Permuting** tensors

In [34]:
# squeezing, removing 1-d's
x_zeros = torch.zeros(size=(1,21,3,4))
print(f"Original shape of the tensor: {x_zeros.shape}")
print(f"Squeeze at the 1st dimension {x_zeros.squeeze(0).shape}")
print(f"Squeeze at the 2nd dimension {x_zeros.squeeze(1).shape}")
print(f"Squeeze at the 3rd dimension {x_zeros.squeeze(2).shape}")
print(f"Squeeze at all dimensions {x_zeros.squeeze().shape}")

Original shape of the tensor: torch.Size([1, 21, 3, 4])
Squeeze at the 1st dimension torch.Size([21, 3, 4])
Squeeze at the 2nd dimension torch.Size([1, 21, 3, 4])
Squeeze at the 3rd dimension torch.Size([1, 21, 3, 4])
Squeeze at all dimensions torch.Size([21, 3, 4])


In [35]:
# add dimension, unsqueez()
x_zeros.unsqueeze(dim=3).shape

torch.Size([1, 21, 3, 1, 4])

In [36]:
# permute, rearange the dimension
# this is also a view
x_zeros.permute(1,0,3,2).shape

torch.Size([21, 1, 4, 3])

# 5. **Indexing** (similar to *NumPy*)
+ when turning from **numpy.array** to **torch.tensor** (and vice versa), the **datatype** prevail

In [13]:
x = torch.arange(0.0,100.,5).reshape(5,2,2)

In [14]:
x[:,0,1]

tensor([ 5., 25., 45., 65., 85.])

In [16]:
x.type(torch.int8)

tensor([[[ 0,  5],
         [10, 15]],

        [[20, 25],
         [30, 35]],

        [[40, 45],
         [50, 55]],

        [[60, 65],
         [70, 75]],

        [[80, 85],
         [90, 95]]], dtype=torch.int8)

# 6. **Reproducibility**
+ Using random seeds to generate **identical random data**
+ Reproduce the code in others' machines

In [3]:
random_TENSOR_a = torch.rand(3,4)
random_TENSOR_b = torch.rand(3,4)

In [4]:
random_TENSOR_a == random_TENSOR_b

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [7]:
torch.manual_seed(seed = 666)
random_TENSOR_a = torch.rand(3,4)

# has to reset the seed every time torch.rand() is called
torch.manual_seed(seed = 666)
random_TENSOR_b = torch.rand(3,4)

random_TENSOR_a == random_TENSOR_b

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# !!!7. **Running tensors on GPUs**

## 7.1. Config GPUs

In [9]:
!nvidia-smi
# check the CUDA satus

Mon Jan  9 01:24:10 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   37C    P8     8W /  N/A |    450MiB /  4096MiB |      9%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [12]:
# check if torch can connect to a GPU
torch.cuda.is_available()

# It's a good practice to write "device agnostic code"
# The code can now ultilizingly run on cpu or gpu
device = "cuda" if torch.cuda.is_available() else "cpu"

In [13]:
device

'cuda'

## 7.1. Transfer tensor to GPU

In [14]:
# get the number of GPU
torch.cuda.device_count()

1

In [15]:
test_TENSOR = torch.tensor([1,2,3])
print(test_TENSOR.device)
print(test_TENSOR.to(device).device)

cpu
cuda:0


In [25]:
TENSOR_GPU = test_TENSOR.to(device)
# TENSOR_GPU = test_TENSOR.cuda() working the same

In [22]:
try:
    TENSOR_GPU.numpy()
except Exception as e:
    print(str(e))

can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.


In [26]:
# copy tensor back to the cpu 
TENSOR_backFromGPU = test_TENSOR.cpu()

In [28]:
TENSOR_backFromGPU.numpy()

array([1, 2, 3])