In [1]:
import torch
torch.__version__

'1.13.1+cu117'

In [2]:
import numpy as np 
np.__version__

'1.24.3'

# 1. **Buidling blocks**
+ scalar = 0-dimension tensor
+ vector = 1-dimension tensor
+ **matrix** vs **tensor**:  
    **matrix** = 2-dimension tensor
=> **Dimension** is how many **nested layers** of **lists** are there in a tensor

In [3]:
# scalar is 0-dimension tensor, 1-dimension vector/matrix
tensor_high = torch.tensor([
        [
            [1,1,2,3],
            [1,2,2,4],
        ],
        [
            [1,1,2,3],
            [1,2,2,4],
        ],
        [
            [1,1,2,3],
            [1,2,2,4],
        ]
    ])
scalar = torch.tensor(1)
print(scalar)
print(f"{scalar.ndim = }")
print(f"{tensor_high.ndim = }")

tensor(1)
scalar.ndim = 0
tensor_high.ndim = 3


In [4]:
# get the value inside a 0-dimension (or a scalar)
# .item() can only work with scalar
print(f"{scalar.item() = }")
try:
    print(f"{tensor_high.item() = }") # will throw error
except Exception as err:
    print(err)


scalar.item() = 1
only one element tensors can be converted to Python scalars


In [5]:
# every element of a tensor has to have equal length
torch.tensor(
    [
    [[1,2,3],[1,2,3],[1,2,3]],
    [[1,2,3],[1,2,3],[1,2,0]]
    ]
)

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 0]]])

In [6]:
TEST_TENSOR = torch.tensor([[2,1],[4,2],[1,2]])

'''
Dimensions in numpy array (or tensors) are number of 
nested elements, or number of nested sets of values:
-> to get the shape of a tensor/array: how the elements are arranged
    + np.array.shape == torch.tensor.shape
-> to get the dimensions a tensor/array
    + np.array.ndim == torch.tensor.ndim
'''
print(f"{TEST_TENSOR.shape = }\n")
print(f"{np.array(TEST_TENSOR).shape = }\n")
print(f"{TEST_TENSOR.ndim = }\n")
print(f"{np.array(TEST_TENSOR).ndim = }\n")

TEST_TENSOR.shape = torch.Size([3, 2])

np.array(TEST_TENSOR).shape = (3, 2)

TEST_TENSOR.ndim = 2

np.array(TEST_TENSOR).ndim = 2



In [7]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                        [[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
MATRIX = torch.tensor([[1,2],[4,5]])

In [8]:
# TENSOR and MATRIX are often uppercase and using interchagebly
# MATRIX is 2 dimensional, -> 2-dimension tensor
print(TENSOR.ndim)
print(MATRIX.ndim)

3
2


# 2. **Gain Momentum**

## **Dummy tensor**

In [9]:
# create a dummy tensor
# the model/sofware will fill in/update that tensor later
RANDOM_TENSORS = torch.rand(size = (3,2,4))
ZEROS_TENSORS = torch.zeros(size = (3,2,4))
ONES_TENSORS = torch.ones(size = (3,2,4))

In [10]:
RANDOM_TENSORS,ZEROS_TENSORS,ONES_TENSORS

(tensor([[[0.4984, 0.4401, 0.2846, 0.9075],
          [0.1119, 0.9037, 0.7529, 0.7300]],
 
         [[0.8648, 0.5590, 0.6621, 0.5348],
          [0.3053, 0.8256, 0.7486, 0.9975]],
 
         [[0.5802, 0.3854, 0.5247, 0.3909],
          [0.0185, 0.8985, 0.7334, 0.0821]]]),
 tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.]]]))

## **Generate range (1-d tensor, vector)**

In [11]:
zero_to_one = torch.arange(0,1,.1)

In [12]:
print(type(zero_to_one))
print(zero_to_one.ndim)

<class 'torch.Tensor'>
1


In [13]:
# create tensors of zeros/ones with the same shape of another tensor
zeros_like = torch.ones_like(input=zero_to_one)
ones_like = torch.zeros_like(input=zero_to_one)
zeros_like,ones_like

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

## **Datatypes**
+ some are better computed on **CPU**, and others, **GPU**
+ default is torch.**float32** (or torch.**float**):
    + torch.**float16** (torch.**half**)
    + torch.**float64** (torch.**double**)

In [14]:
# Returns the number of GPUs available
torch.cuda.device_count()

/home/durian/.local/lib/python3.10/site-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")


0

In [15]:
# Default datatype for tensors is float32
# Default device is cpu
float_32_tensor = torch.tensor([3.0, 6.0, 9.0])

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [16]:
# assign a floating float16 tensor to gpu
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16,
                               device="cuda") 

float_16_tensor.type(),float_16_tensor.device

RuntimeError: No CUDA GPUs are available

+ **When ever** there's a problem, it is usually related to one of these three:
    + **Where** is my tensor **stored**
    + What is the **shape** of my tensor (most of the time)
    + What is the **type** of *my tensor*

# 3. **Operations**

In [ ]:
import torch

## 3.1. Basics

In [ ]:
vector = torch.tensor([1,2,3])
print(vector + 10)
print(vector - 10)
print(vector * vector)
print(vector / 10)

## 3.2.Multiplication

### 3.2.1. **Matrix** multiplication => create **dot product**

In [ ]:
test_TENSOR_1 = torch.rand(size = (2,3))
test_TENSOR_2 = torch.rand(size = (3,4))

In [ ]:
# can only be done with the number of rows equal to number of columns
print(test_TENSOR_1 @ test_TENSOR_2) # using @ 
# using torch.matmul()
# torch.mm() has the same effect
print(torch.matmul(test_TENSOR_1,test_TENSOR_2)) 

try:
    test_TENSOR_2 @ test_TENSOR_1
except Exception as e:
    print(str(e)+"\n")



### 3.2.2. **Element-wise** multiplication

In [ ]:
try:
    test_TENSOR_1 * test_TENSOR_2
except Exception as e:
    print(e)

# multication among individual values of 2 matrix
# => 2 matrices have to have to same size 

test_TENSOR_1 * torch.tensor([[1,2,3],[1,4,1]])


## 3.3. **Tensor aggregations** (min, max, mean, median, sum, etc.)

### 3.3.1. **Basics**

In [ ]:
import torch

In [ ]:
test_MATRIX = torch.tensor([
                [1,2,1],
                [1,54,4],
                [1,9,6]
                ],dtype=torch.float)

In [ ]:
print(torch.mean(test_MATRIX),test_MATRIX.mean())
print(torch.sum(test_MATRIX),test_MATRIX.sum())
print(torch.max(test_MATRIX),test_MATRIX.max())
print(torch.min(test_MATRIX),test_MATRIX.min())

### 3.3.2. Find **positional min and max**

In [ ]:
print(
    test_MATRIX.argmax(dim=1,keepdim=True),
    test_MATRIX.argmax(dim=0,keepdim=True)
    )

In [ ]:
test_MATRIX[0,2]

# 4. **Changing the shape of the tensor**
+ **Reshapping** - reshape input into a redefined shape (**change memory**)
+ **View** - new tensor is **NOT** created => using the **same memory slots** as the input tensor
+ **Stacking** - merge multiple tensors (**horizontally** or **vertically**)
+ **Squeeze** - removes all 1-d's from a tensor ???
+ **Unsqueeze** - add a 1-d to a target tensor
+ **Permute** - return a **view** of the input tensor, but **dimensions permuted (swappedd)** in a particular way

## 4.1. **Reshaping**

In [ ]:
x = torch.arange(0,100,1)
x,x.shape

In [ ]:
# RESHAPE, add an extra dimension
x_reshape = x.reshape(1,100)
x_reshape.shape

In [ ]:
# the shape has to fit all the original value
try:
    x_reshape = x.reshape(1,99)
except Exception as e:
    print(str(e))

# shape of 10,2,5
# 3 tensors
x_reshape = x.reshape(10,2,5)
print(f"{x_reshape.shape = }")

print(f"{x_reshape.ndim = }")

## 4.2. **View**

In [ ]:
# just like the reshaping, but there's not memmory wasted
x_view = x.view(2,2,25)
print(f"{x_view.shape = }")
print(f"{x_view.ndim = }")

In [ ]:
# changing a view with change the input tensor
## at the index 0 of first tensor, 0 of second tensor
## change the value of the 1 and 2-indexed scalar to 99 and 99
x_view[0,0,1:3] = torch.tensor([99,99])

# check the input tensor
x[0:5]

## 4.3. **Stack**

In [ ]:
# create new dimension
# change the shape
print(f"{torch.stack([x,x],dim=0).shape = }")
print(f"{torch.stack([x,x],dim=1).shape = }")

In [ ]:
# the tensor can only be stacked on existing dimension
## In this example, x_reshape has 3 dimensions
## => can be stacked in 4 different dimension
print(f"{torch.stack([x_reshape,x_reshape],dim=0).shape = }")
print(f"{torch.stack([x_reshape,x_reshape],dim=1).shape = }")
print(f"{torch.stack([x_reshape,x_reshape],dim=2).shape = }")
print(f"{torch.stack([x_reshape,x_reshape],dim=3).shape = }")

## 4.4. **Squeezing** and **Permuting** tensors

In [ ]:
# squeezing, removing 1-d's
x_zeros = torch.zeros(size=(1,21,3,4))
print(f"Original shape of the tensor: {x_zeros.shape}")
print(f"Squeeze at the 1st dimension {x_zeros.squeeze(0).shape}")
print(f"Squeeze at the 2nd dimension {x_zeros.squeeze(1).shape}")
print(f"Squeeze at the 3rd dimension {x_zeros.squeeze(2).shape}")
print(f"Squeeze at all dimensions {x_zeros.squeeze().shape}")

In [ ]:
# add dimension, unsqueez()
x_zeros.unsqueeze(dim=3).shape

In [ ]:
# permute, rearange the dimension
# this is also a view
x_zeros.permute(1,0,3,2).shape

# 5. **Indexing** (similar to *NumPy*)
+ when turning from **numpy.array** to **torch.tensor** (and vice versa), the **datatype** prevail

In [ ]:
x = torch.arange(0.0,100.,5).reshape(5,2,2)

In [ ]:
x[:,0,1]

In [ ]:
x.type(torch.int8)

# 6. **Reproducibility**
+ Using random seeds to generate **identical random data**
+ Reproduce the code in others' machines

In [ ]:
random_TENSOR_a = torch.rand(3,4)
random_TENSOR_b = torch.rand(3,4)

In [ ]:
random_TENSOR_a == random_TENSOR_b

In [ ]:
torch.manual_seed(seed = 666)
random_TENSOR_a = torch.rand(3,4)

# has to reset the seed every time torch.rand() is called
torch.manual_seed(seed = 666)
random_TENSOR_b = torch.rand(3,4)

random_TENSOR_a == random_TENSOR_b

# !!!7. **Running tensors on GPUs**

## 7.1. Config GPUs

In [ ]:
!nvidia-smi
# check the CUDA satus

In [ ]:
# check if torch can connect to a GPU
torch.cuda.is_available()

# It's a good practice to write "device agnostic code"
# The code can now ultilizingly run on cpu or gpu
device = "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
device

## 7.1. Transfer tensor to GPU

In [ ]:
# get the number of GPU
torch.cuda.device_count()

In [ ]:
test_TENSOR = torch.tensor([1,2,3])
print(test_TENSOR.device)
print(test_TENSOR.to(device).device)

In [ ]:
TENSOR_GPU = test_TENSOR.to(device)
# TENSOR_GPU = test_TENSOR.cuda() working the same

In [ ]:
try:
    TENSOR_GPU.numpy()
except Exception as e:
    print(str(e))

In [ ]:
# copy tensor back to the cpu 
TENSOR_backFromGPU = test_TENSOR.cpu()

In [ ]:
TENSOR_backFromGPU.numpy()